### 예약 생성
POST http://localhost:8080/reservations
Content-Type: application/json

{
  "date": "2024-08-05",
  "name": "브라운",
  "timeId": 1,
  "themeId": 1
}

### 모든 예약 조회
GET http://localhost:8080/reservations

### 예약 id 조회
GET http://localhost:8080/reservations/1

### 예약 조건부 조회
GET /reservations?memberId=1&themeId=1&dateFrom=2020-01-01&dateTo=2025-01-01

### 예약 가능 시간 조회
GET http://localhost:8080/reservations/times

### 예약 id 삭제
DELETE http://localhost:8080/reservations/2
