package roomescape;

public class TokenTestFixture {

    public static final String ADMIN_TOKEN = "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwibmFtZSI6Iuq0gOumrOyekCIsImVtYWlsIjoiYWRtaW5AYS5jb20iLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MTUzOTQxNjd9.Yo7qekkF8XyQiCeWQj5AfQ5rrN3J9kCtwk3QPi7pAJA";
    public static final String USER_TOKEN = "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyIiwibmFtZSI6IuyCrOyaqeyekCIsImVtYWlsIjoidXNlckBhLmNvbSIsInJvbGUiOiJVU0VSIiwiZXhwIjoxNzE1Mzk0MTY3fQ.S5kRPwa4au_2Bsnexp928fIDir5p753UK6UFF8iEFI8";
}
