CREATE TABLE `theme` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(255) NOT NULL,
    `description` VARCHAR(255) NULL,
    `image_url` VARCHAR(255) NULL,
    `required_time` TIME NOT NULL,
    CONSTRAINT `PK_THEME` PRIMARY KEY (`id`)
);

CREATE TABLE `user` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(255) NOT NULL,
    `role` VARCHAR(30) NOT NULL,
    CONSTRAINT `PK_USER` PRIMARY KEY (`id`)
);

CREATE TABLE `schedule` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `theme_id` BIGINT NOT NULL,
    `start_at` DATETIME NOT NULL,
    `end_at` DATETIME NOT NULL,
    CONSTRAINT `PK_SCHEDULE` PRIMARY KEY (`id`),
    CONSTRAINT `FK_SCHEDULE_THEME` FOREIGN KEY (`theme_id`) REFERENCES `THEME` (`id`)
);

CREATE TABLE `reservation` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `user_id` BIGINT NOT NULL,
    `schedule_id` BIGINT NOT NULL,
    CONSTRAINT `PK_RESERVATION` PRIMARY KEY (`id`),
    CONSTRAINT `FK_RESERVATION_USER` FOREIGN KEY (`user_id`) REFERENCES `USER` (`id`),
    CONSTRAINT `FK_RESERVATION_SCHEDULE` FOREIGN KEY (`schedule_id`) REFERENCES `SCHEDULE` (`id`)
);
