package roomescape.user.infrastructure.fake;

import java.util.HashMap;
import java.util.Map;
import java.util.Optional;
import roomescape.user.application.repository.UserRepository;
import roomescape.user.domain.User;

public class FakeUserDao implements UserRepository {

    private Long autoGeneratedId = 0L;
    private final Map<Long, User> store = new HashMap<>();

    public void insert(User user) {
        store.put(autoGeneratedId++, user);
    }

    @Override
    public Optional<User> findByEmail(String email) {
        return store.values().stream()
                .filter(user -> user.getEmail().equals(email))
                .findAny();
    }
}
