### 로그인 API
POST /login
Host: localhost:8080
Content-Type: application/json

{
  "password": "password",
  "email": "admin@email.com"
}

### 로그아웃 API
POST /logout
Host: localhost:8080
Cookie: _ga=GA1.1.48222725.1666268105; _ga_QD3BVX7MKT=GS1.1.1687746261.15.1.1687747186.0.0.0; Idea-25a74f9c=3cbc3411-daca-48c1-8201-51bdcdd93164; token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBlbWFpbC5jb20iLCJpYXQiOjE3MTU0MjI0NzUsImV4cCI6MTcxNTQyNjA3NX0.eP4KsZ8YZ0jMKy0dTl9HywQGSaCeQjyBtHZQ1TGIU3c

### 인증 정보 조회 API
GET /login/check
Host: localhost:8080
Cookie: _ga=GA1.1.48222725.1666268105; _ga_QD3BVX7MKT=GS1.1.1687746261.15.1.1687747186.0.0.0; Idea-25a74f9c=3cbc3411-daca-48c1-8201-51bdcdd93164; token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwibmFtZSI6IuyWtOuTnOuvvCIsInJvbGUiOiJBRE1JTiJ9.vcK93ONRQYPFCxT5KleSM6b7cl1FE-neSLKaFyslsZM
