### 테마 등록
POST http://localhost:8080/admin/themes
Content-Type: application/json

{
  "name": "방탈출 1",
  "description": "설명 1",
  "thumbnailUrl": "thumbnail.jpg"
}

### 시간 등록
POST localhost:8080/times
Content-Type: application/json

{
  "startAt": "10:00"
}

### 예약 등록
POST localhost:8080/reservations
Content-Type: application/json

{
  "name": "LSJ",
  "date": "2026-05-08",
  "timeId": 1,
  "themeId": 1
}
