###
POST http://localhost:8080/reservations
Content-Type: application/json

{
  "name": "새양",
  "date": "2024-05-31",
  "timeId": 1,
  "themeId": 1
}

###
POST http://localhost:8080/reservations
Content-Type: application/json

{
  "name": "레디",
  "date": "2024-05-31",
  "timeId": 2,
  "themeId": 1
}

###
POST http://localhost:8080/reservations
Content-Type: application/json

{
  "name": "낙낙",
  "date": "2024-05-31",
  "timeId": 1,
  "themeId": 2
}
