### 예약 목록 조회 API
GET http://localhost:8080/reservations

### 예약 추가 API
POST http://localhost:8080/reservations
cookie: token=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxMDAxIiwibmFtZSI6IuyerOymiCIsInJvbGUiOiJNRU1CRVIifQ.rPCGV4wukOyeBy59Ks_VlanyyUStDDjj6gs89sLzE_FeAcXYqD2iuNWFWSaETFb7S58w6bD7njhQpzJhwOydJw;
host: localhost:8080
Content-Type: application/json

{
  "date": "2100-01-21",
  "themeId": 1002,
  "timeId": 1001
}

### 어드민 예약 추가 API
POST http://localhost:8080/admin/reservations
cookie: token=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxMDA4IiwibmFtZSI6IuyWtOuTnOuvvCIsInJvbGUiOiJBRE1JTiJ9.QBXPFjmHn0iteRzHlr0Pml3EJLOOW8QKYcT8FY9sTszJluHU0hC3frCUNIEc5A5h0hmJFZD1e4j2y3aj5u8uDg;
host: localhost:8080
Content-Type: application/json

{
  "memberId": 1004,
  "themeId": 1001,
  "date": "2100-01-22",
  "timeId": 1001
}

### 예약 삭제 API
DELETE http://localhost:8080/reservations/1
