### 예약 시간 목록 조회 API (접근 권한: 관리자)
GET {{base-url}}/times

### 예약 가능 시간 목록 조회 API
GET {{base-url}}/times/available?date=2024-10-11&theme-id=1

### 예약 시간 추가 API (접근 권한: 관리자)
POST {{base-url}}/times
Content-Type: application/json

{
  "startAt": "10:00"
}

### 예약 시간 삭제 API (접근 권한: 관리자)
DELETE {{base-url}}/times/1
