package roomescape.member.infrastructure.fake;

import java.util.HashMap;
import java.util.Map;
import java.util.Optional;
import roomescape.member.application.repository.MemberRepository;
import roomescape.member.domain.Member;

public class FakeMemberDao implements MemberRepository {

    private Long autoGeneratedId = 0L;
    private final Map<Long, Member> store = new HashMap<>();

    public void insert(Member member) {
        store.put(autoGeneratedId++, member);
    }

    @Override
    public Optional<Member> findByEmail(String email) {
        return store.values().stream()
                .filter(user -> user.getEmail().equals(email))
                .findAny();
    }
}
