package roomescape.member.infrastructure.fake;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import roomescape.member.application.dto.CreateMemberRequest;
import roomescape.member.application.dto.GetMemberResponse;
import roomescape.member.application.repository.MemberRepository;
import roomescape.member.domain.Member;

public class FakeMemberDao implements MemberRepository {

    private Long autoGeneratedId = 0L;
    private final Map<Long, Member> store = new HashMap<>();

    public void insert(Member member) {
        store.put(autoGeneratedId++, member);
    }

    @Override
    public Optional<Member> findByEmail(String email) {
        return store.values().stream()
                .filter(user -> user.getEmail().equals(email))
                .findAny();
    }

    @Override
    public Member insert(CreateMemberRequest request) {
        long id = autoGeneratedId++;
        Member member = new Member(id,
                request.name(),
                request.email(),
                request.password(),
                request.role()
        );
        store.put(id, member);
        return member;
    }

    @Override
    public Optional<Member> findById(Long id) {
        return Optional.ofNullable(store.get(id));
    }

    @Override
    public List<GetMemberResponse> findAll() {
        return store.values().stream()
                .map(member -> new GetMemberResponse(member.getId(), member.getName()))
                .toList();
    }
}
