### 예약 조회 API

GET http://localhost:8080/reservations

### 예약 추가 API

POST http://localhost:8080/reservations
Content-Type: application/json

{
  "name": "러너덕",
  "date": "2024-05-10",
  "timeId": 1,
  "themeId": 1
}

### 예약 삭제 API

DELETE http://localhost:8080/reservations/1
