### 테마 조회 API

GET http://localhost:8080/themes

### 테마 추가 API

POST http://localhost:8080/themes
Content-Type: application/json

{
  "name": "레벨2 탈출",
  "description": "우테코 레벨2를 탈출하는 내용입니다.",
  "thumbnail": "https://i.pinimg.com/236x/6e/bc/46/6ebc461a94a49f9ea3b8bbe2204145d4.jpg"
}

### 최근 1주일 기준 인기 테마 10개 조회 API

GET http://localhost:8080/themes/popular

### 테마 삭제 API

DELETE http://localhost:8080/themes/1
