POST /members HTTP/1.1
content-type: application/json
host: localhost:8080

{
  "email": "admin@email.com",
  "password": "password",
  "name": "히스타"
}

###
POST /login HTTP/1.1
content-type: application/json
host: localhost:8080

{
  "password": "password",
  "email": "admin@email.com"
}

###
GET /login/check HTTP/1.1
cookie: _ga=GA1.1.48222725.1666268105; _ga_QD3BVX7MKT=GS1.1.1687746261.15.1.1687747186.0.0.0; Idea-25a74f9c=3cbc3411-daca-48c1-8201-51bdcdd93164; token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwibmFtZSI6IuyWtOuTnOuvvCIsInJvbGUiOiJBRE1JTiJ9.vcK93ONRQYPFCxT5KleSM6b7cl1FE-neSLKaFyslsZM
host: localhost:8080
