INSERT INTO RESERVATION_TIME(START_AT)
VALUES ('23:00');

INSERT INTO THEME(NAME, DESCRIPTION, THUMBNAIL)
VALUES ('테마1', '설명1', '썸네일1');

INSERT INTO MEMBER(NAME, EMAIL, PASSWORD, ROLE)
VALUES ('레모네', 'lemone@wooteco.com', 'lemone1234', 'ADMIN')
