DROP TABLE IF EXISTS RESERVATION;
DROP TABLE IF EXISTS THEME;
DROP TABLE IF EXISTS RESERVATION_TIME;
DROP TABLE IF EXISTS MEMBER;

CREATE TABLE IF NOT EXISTS MEMBER
(
    id   BIGINT       NOT NULL AUTO_INCREMENT,
    role VARCHAR(30) NOT NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS reservation_time
(
    id   BIGINT       NOT NULL AUTO_INCREMENT,
    start_at VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS theme
(
    id          BIGINT       NOT NULL AUTO_INCREMENT,
    name        VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    thumbnail VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS reservation
(
    id   BIGINT       NOT NULL AUTO_INCREMENT,
    member_id BIGINT,
    date VARCHAR(255) NOT NULL,
    time_id BIGINT,
    theme_id BIGINT,
    PRIMARY KEY (id),
    FOREIGN KEY (member_id) REFERENCES MEMBER (id),
    FOREIGN KEY (time_id) REFERENCES RESERVATION_TIME (id),
    FOREIGN KEY (theme_id) REFERENCES THEME (id)
);
