package roomescape.exception;

public enum ErrorCode {
    BAD_REQUEST,

    INVALID_INPUT,
    INVALID_REQUEST,
    INVALID_ID,
    INVALID_DURATION,
    INVALID_RESERVATION,
    INVALID_RESERVATION_TIME,
    INVALID_THEME,

    TIME_IN_USE,
    THEME_IN_USE,
    DATA_INTEGRITY_VIOLATION,

    PAST_RESERVATION,
    NOT_RESERVATION_OWNER,

    RESERVATION_NOT_FOUND,
    RESERVATION_TIME_NOT_FOUND,
    THEME_NOT_FOUND,

    DUPLICATE_RESERVATION,

    DATABASE_ERROR,
    INTERNAL_SERVER_ERROR,
}
