package roomescape.exception;

public enum ErrorCode {
    DATA_CONFLICT,
    INTERNAL_SERVER_ERROR,
    INVALID_DATE_FORMAT,
    INVALID_ENUM_VALUE,
    INVALID_INPUT,
    INVALID_THEME_NAME,
    INVALID_TIME_FORMAT,
    INVALID_TYPE_VALUE,
    MALFORMED_JSON,
    MY_RESERVATION_NOT_FOUND,
    PAST_RESERVATION_CANNOT_BE_CANCELLED,
    PAST_RESERVATION_CANNOT_BE_UPDATED,
    RESERVATION_DATE_REQUIRED,
    RESERVATION_DATE_TIME_IN_PAST,
    RESERVATION_DUPLICATED,
    RESERVATION_NAME_REQUIRED,
    RESERVATION_NAME_TOO_LONG,
    RESERVATION_TIME_DUPLICATED,
    RESERVATION_TIME_ID_REQUIRED,
    RESERVATION_TIME_IN_USE,
    RESERVATION_TIME_NOT_FOUND,
    RESERVATION_TIME_REQUIRED,
    RESOURCE_NOT_FOUND,
    THEME_ID_REQUIRED,
    THEME_IN_USE,
    THEME_NAME_DUPLICATED,
    THEME_NOT_FOUND;

    public String getCode() {
        return name();
    }
}
