### GET request to example server
GET localhost:8080/themes

###
GET localhost:8080/reservations

###
POST http://localhost:8080/reservations
Content-Type: application/json

{
  "name": "tooda",
  "date": "2025-06-25",
  "timeId": 1,
  "themeId": 1
}

<> 2025-04-30T141421.400.json
<> 2025-04-30T141318.400.json
<> 2025-04-30T141257.400.json

###
POST http://localhost:8080/times
Content-Type: application/json

{
  "startAt": "10:01"
}

<> 2025-04-30T141328.400.txt

###
POST http://localhost:8080/themes
Content-Type: application/json

{
  "name": "공포",
  "description": "무서운 테마",
  "thumbnail": "thumbnail"
}

###
GET http://localhost/admin

###
GET http://localhost:8080/admin/theme

###
GET http://localhost:8080/admin/theme

<> 2025-04-30T135328.200.html

###
DELETE http://localhost:8080/themes/1

<> 2025-04-30T135547.405.json

<> 2025-04-30T141542.201.json
<> 2025-04-30T141314.201.json
<> 2025-04-30T141252.201.json
<> 2025-04-30T141237.201.json

###
GET http://localhost:8080/times

<> 2025-04-30T141358.200.json

###
GET http://localhost:8080/themes

