package roomescape.dto.error;

public enum ErrorCode {
    INVALID_INPUT,
    PAST_RESERVATION,
    DUPLICATE_RESERVATION,
    RESERVATION_NOT_FOUND,
    RESERVATION_TIME_NOT_FOUND,
    RESERVATION_TIME_IN_USE,
    UNAUTHORIZED_RESERVATION,
    INVALID_REQUEST_FORMAT,
    INTERNAL_SERVER_ERROR
}
